/**
 * lib/db/scripts/verify_upgrade_proration.cjs — Test script that verifies the Stripe subscription upgrade flow with proration by creating a test customer, subscription swap, and inspecting the resulting invoice.
 * Author: Pasquale Marzaioli
 */
// One-shot verification script for the Basic -> Premium subscription swap.
//
// Mirrors exactly what sito/artifacts/api-server/src/routes/checkout.ts does on
// POST /api/checkout/upgrade. Creates a throwaway Stripe test-mode customer,
// pays for a Basic subscription, swaps the item to Premium with proration,
// inspects the resulting invoice, and cleans everything up.

const fs = require("fs");
const path = require("path");
const Stripe = require("stripe");

const ENV_FILE = path.resolve(__dirname, "../../../.env");
for (const line of fs.readFileSync(ENV_FILE, "utf8").split("\n")) {
  const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
  if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^['"]|['"]$/g, "");
}

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);
const BASIC = process.env.STRIPE_PRICE_BASIC;
const PREMIUM = process.env.STRIPE_PRICE_PREMIUM;

function fmt(c, cur) {
  if (typeof c !== "number") return String(c);
  return `${(c / 100).toFixed(2)} ${cur ? cur.toUpperCase() : ""}`.trim();
}

async function main() {
  console.log("== verify_upgrade_proration ==");
  console.log("Basic price:  ", BASIC);
  console.log("Premium price:", PREMIUM);

  const basicPrice = await stripe.prices.retrieve(BASIC);
  const premiumPrice = await stripe.prices.retrieve(PREMIUM);
  console.log(
    "  Basic   = ",
    fmt(basicPrice.unit_amount, basicPrice.currency),
    "every",
    basicPrice.recurring?.interval_count,
    basicPrice.recurring?.interval,
  );
  console.log(
    "  Premium = ",
    fmt(premiumPrice.unit_amount, premiumPrice.currency),
    "every",
    premiumPrice.recurring?.interval_count,
    premiumPrice.recurring?.interval,
  );
  if (
    basicPrice.recurring?.interval !== "month" ||
    basicPrice.recurring?.interval_count !== 3 ||
    premiumPrice.recurring?.interval !== "month" ||
    premiumPrice.recurring?.interval_count !== 3
  ) {
    console.warn(
      "  ⚠️  prices are not configured as 3-month recurring — proration math will still work but the cycle won't match the doc.",
    );
  }

  const customer = await stripe.customers.create({
    email: `proration-test+${Date.now()}@example.com`,
    name: "CarbonEYE proration test",
    metadata: { purpose: "automated-verify_upgrade_proration" },
  });
  console.log("Created customer:", customer.id);

  const pm = await stripe.paymentMethods.attach("pm_card_visa", { customer: customer.id });
  await stripe.customers.update(customer.id, {
    invoice_settings: { default_payment_method: pm.id },
  });

  const subscription = await stripe.subscriptions.create({
    customer: customer.id,
    items: [{ price: BASIC }],
    payment_behavior: "default_incomplete",
    expand: ["latest_invoice.payment_intent"],
  });
  console.log("Created Basic subscription:", subscription.id, "status=", subscription.status);

  // Pay the first invoice so the sub is fully active before we update it.
  const firstInvoiceId = subscription.latest_invoice?.id ?? subscription.latest_invoice;
  if (firstInvoiceId) {
    const paid = await stripe.invoices.pay(firstInvoiceId, { payment_method: pm.id });
    console.log(
      "  initial invoice paid:",
      paid.id,
      "amount=",
      fmt(paid.amount_paid, paid.currency),
    );
  }

  const active = await stripe.subscriptions.retrieve(subscription.id);
  const itemId = active.items.data[0]?.id;
  if (!itemId) throw new Error("Active subscription has no line item.");

  console.log("\nSwapping item -> Premium with proration_behavior=always_invoice ...");
  const updated = await stripe.subscriptions.update(subscription.id, {
    items: [{ id: itemId, price: PREMIUM }],
    proration_behavior: "always_invoice",
  });
  console.log("Updated subscription:", updated.id, "status=", updated.status);
  console.log("  current line item price:", updated.items.data[0]?.price?.id);
  console.log(
    "  current_period_end (unchanged renewal):",
    new Date((updated.items.data[0]?.current_period_end ?? updated.current_period_end ?? 0) * 1000).toISOString(),
  );

  // Find the proration invoice generated by the swap.
  const invoices = await stripe.invoices.list({ subscription: subscription.id, limit: 5 });
  console.log("\nInvoices on this subscription (most recent first):");
  let prorationFound = false;
  for (const inv of invoices.data) {
    console.log(
      `  - ${inv.id} status=${inv.status} total=${fmt(inv.total, inv.currency)}  lines=${inv.lines.data.length}`,
    );
    for (const line of inv.lines.data) {
      const isProration = line.proration === true;
      if (isProration) prorationFound = true;
      console.log(
        `      • ${isProration ? "PRORATION" : "line"}  ${fmt(line.amount, line.currency)}  price=${line.price?.id}  desc="${line.description}"`,
      );
    }
  }

  console.log("\nResult:", prorationFound ? "✅ proration invoice generated" : "❌ no proration line item found");

  console.log("\nCleaning up...");
  await stripe.subscriptions.cancel(subscription.id).catch((e) => console.warn("cancel failed:", e.message));
  await stripe.customers.del(customer.id).catch((e) => console.warn("customer delete failed:", e.message));
  console.log("Done.");

  if (!prorationFound) process.exitCode = 1;
}

main().catch((err) => {
  console.error("FAILED:", err.message);
  process.exitCode = 1;
});
