/**
 * lib/api-client-react/src/certificate-requests.ts — Typed React Query API client with hooks for the certificate request human-in-the-loop approval workflow (submit, poll, admin actions), hand-written to integrate shared types from @workspace/carboneye-types.
 * Author: Pasquale Marzaioli
 */
/**
 * sito/lib/api-client-react/src/certificate-requests.ts
 *
 * Typed API client and React Query hooks for the CarbonEYE certificate request
 * human-in-the-loop approval workflow.
 *
 * This file is hand-written (not generated by orval) because it imports shared
 * types from @workspace/carboneye-types — the source of truth for the workflow
 * types shared between the TypeScript API (api-ts/) and the sito/ frontend.
 *
 * Code style mirrors the orval-generated `generated/api.ts` exactly:
 *   - Plain async functions for every HTTP call (URL helper + fetcher + options helper)
 *   - Separate Result/Error type aliases for each operation
 *   - React Query hooks via useQuery (for GETs) and useMutation (for POSTs)
 *
 * IMPORTANT: Do NOT move types into generated/api.schemas.ts — those files are
 * overwritten by orval. Types live in @workspace/carboneye-types instead.
 *
 * Admin endpoints authenticate via the X-Admin-Secret request header.
 * User-facing endpoints use standard session cookies (no token needed in code).
 */

import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

// Import shared canonical types from the workspace types package.
// These mirror the Cosmos DB document shape and are the single source of truth
// for the certificate request workflow across api-ts/ and sito/.
import type {
  CertificateRequest,
  SubmitCertificateRequestBody,
  SubmitCertificateRequestResponse,
} from "@workspace/carboneye-types";

import { customFetch } from "./custom-fetch";
import type { ErrorType, BodyType } from "./custom-fetch";

// ---------------------------------------------------------------------------
// Internal utility types — replicated from the orval-generated pattern so
// this file is self-contained and consistent with generated/api.ts.
// ---------------------------------------------------------------------------

/** Unwraps a value or promise to its resolved type. */
type AwaitedInput<T> = PromiseLike<T> | T;
type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/** Extracts the type of the second parameter of a function. */
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

// ===========================================================================
// USER-FACING ENDPOINTS
// ===========================================================================

// ---------------------------------------------------------------------------
// POST /api/certificate-requests — Submit a new certificate request
// ---------------------------------------------------------------------------

/**
 * Returns the canonical URL for submitting a certificate request.
 * Kept as a separate helper so consumers can construct query keys consistently.
 */
export const getSubmitCertificateRequestUrl = (): string => {
  return `/api/certificate-requests`;
};

/**
 * Submits a new certificate request to the CarbonEYE API.
 *
 * The pipeline does NOT run immediately — the request is placed in "submitted"
 * state and waits for an admin to trigger analysis from the admin dashboard.
 * The company should poll `getCertificateRequest` to track status changes.
 *
 * @param body   - Company name, coordinates, date range and optional period_days.
 * @param options - Optional fetch overrides (signal, extra headers, etc.).
 * @returns      The 202 response containing request_id and submitted_at.
 */
export const submitCertificateRequest = async (
  body: SubmitCertificateRequestBody,
  options?: RequestInit,
): Promise<SubmitCertificateRequestResponse> => {
  return customFetch<SubmitCertificateRequestResponse>(
    getSubmitCertificateRequestUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(body),
    },
  );
};

/**
 * Builds the useMutation options object for submitCertificateRequest.
 * Separates mutation configuration from hook invocation so consumers can
 * re-use the options in server-action contexts as well as React components.
 */
export const getSubmitCertificateRequestMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitCertificateRequest>>,
    TError,
    { data: BodyType<SubmitCertificateRequestBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof submitCertificateRequest>>,
  TError,
  { data: BodyType<SubmitCertificateRequestBody> },
  TContext
> => {
  const mutationKey = ["submitCertificateRequest"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof submitCertificateRequest>>,
    { data: BodyType<SubmitCertificateRequestBody> }
  > = (props) => {
    const { data } = props ?? {};
    return submitCertificateRequest(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

/** Type alias for the resolved return value of submitCertificateRequest. */
export type SubmitCertificateRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof submitCertificateRequest>>
>;
/** Type alias for the mutation variable type. */
export type SubmitCertificateRequestMutationBody =
  BodyType<SubmitCertificateRequestBody>;
/** Type alias for the mutation error type. */
export type SubmitCertificateRequestMutationError = ErrorType<void>;

/**
 * React Query mutation hook for submitting a new certificate request.
 *
 * Usage:
 * ```tsx
 * const { mutate, isPending } = useSubmitCertificateRequest();
 * mutate({ data: { company_name, coordinates, date_range } });
 * ```
 *
 * @param options - Optional mutation options and request overrides.
 * @returns       UseMutationResult with data typed as SubmitCertificateRequestResponse.
 */
export const useSubmitCertificateRequest = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof submitCertificateRequest>>,
    TError,
    { data: BodyType<SubmitCertificateRequestBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof submitCertificateRequest>>,
  TError,
  { data: BodyType<SubmitCertificateRequestBody> },
  TContext
> => {
  return useMutation(getSubmitCertificateRequestMutationOptions(options));
};

// ---------------------------------------------------------------------------
// GET /api/certificate-requests/{requestId} — Poll request status
// ---------------------------------------------------------------------------

/**
 * Returns the canonical URL for fetching a single certificate request.
 *
 * @param requestId - The request_id returned by POST /certificate-requests.
 */
export const getGetCertificateRequestUrl = (requestId: string): string => {
  return `/api/certificate-requests/${requestId}`;
};

/**
 * Fetches a single certificate request by ID.
 *
 * Companies call this endpoint to poll for status changes through the
 * human-in-the-loop approval flow:
 *   submitted → analyzing → pending_approval → approved | rejected
 *
 * Optional fields (esg_score, pdf_blob_name, etc.) are only present once the
 * admin has triggered analysis and the pipeline has completed.
 *
 * @param requestId - The request_id returned by POST /certificate-requests.
 * @param options   - Optional fetch overrides (signal for abort, etc.).
 * @returns         The full CertificateRequest document.
 */
export const getCertificateRequest = async (
  requestId: string,
  options?: RequestInit,
): Promise<CertificateRequest> => {
  return customFetch<CertificateRequest>(
    getGetCertificateRequestUrl(requestId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Builds the React Query key for a specific certificate request.
 * Stable query keys allow cache invalidation from admin hooks after
 * approve/reject actions.
 *
 * @param requestId - The certificate request ID.
 */
export const getGetCertificateRequestQueryKey = (
  requestId: string,
): readonly [string] => {
  return [`/api/certificate-requests/${requestId}`] as const;
};

/**
 * Builds the full useQuery options object for getCertificateRequest.
 * Separates options construction from hook invocation — useful for prefetching
 * in server components (e.g. Next.js `dehydrate`).
 *
 * @param requestId - The certificate request ID.
 * @param options   - Optional query options and request overrides.
 */
export const getGetCertificateRequestQueryOptions = <
  TData = Awaited<ReturnType<typeof getCertificateRequest>>,
  TError = ErrorType<unknown>,
>(
  requestId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getCertificateRequest>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  // Merge any caller-provided queryKey override with the canonical key.
  const queryKey =
    queryOptions?.queryKey ?? getGetCertificateRequestQueryKey(requestId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCertificateRequest>>
  > = ({ signal }) =>
    getCertificateRequest(requestId, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCertificateRequest>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

/** Type alias for the resolved return value of getCertificateRequest. */
export type GetCertificateRequestQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCertificateRequest>>
>;
/** Type alias for the query error type. */
export type GetCertificateRequestQueryError = ErrorType<unknown>;

/**
 * React Query hook for polling a certificate request by ID.
 *
 * Automatically re-fetches on stale data. Consumers can configure
 * `refetchInterval` to poll until the status reaches a terminal state.
 *
 * Usage:
 * ```tsx
 * const { data, isLoading } = useGetCertificateRequest(requestId, {
 *   query: { refetchInterval: (q) =>
 *     q.state.data?.status === 'approved' ? false : 5000
 *   },
 * });
 * ```
 *
 * Pass `null` as `requestId` to disable fetching (enabled: false behaviour).
 *
 * @param requestId - The certificate request ID, or null to disable the query.
 * @param options   - Optional query options and request overrides.
 * @returns         UseQueryResult with data typed as CertificateRequest.
 */
export function useGetCertificateRequest<
  TData = Awaited<ReturnType<typeof getCertificateRequest>>,
  TError = ErrorType<unknown>,
>(
  requestId: string | null,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getCertificateRequest>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  // Disable the query entirely when requestId is null — avoids fetching on
  // an undefined ID before the user has submitted a request.
  const queryOptions = getGetCertificateRequestQueryOptions(
    requestId ?? "",
    {
      ...options,
      query: {
        ...options?.query,
        queryKey: options?.query?.queryKey ?? getGetCertificateRequestQueryKey(requestId ?? ""),
        enabled: requestId != null && (options?.query?.enabled ?? true),
      },
    },
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

// ===========================================================================
// ADMIN-FACING ENDPOINTS
// All admin operations require the X-Admin-Secret header for authentication.
// The secret is passed explicitly rather than via the module-level auth getter
// so that admin pages can manage the secret independently from user sessions.
// ===========================================================================

// ---------------------------------------------------------------------------
// GET /api/admin/certificate-requests — List all requests
// ---------------------------------------------------------------------------

/**
 * Returns the canonical URL for the admin certificate requests list endpoint.
 */
export const getAdminListRequestsUrl = (): string => {
  return `/api/admin/certificate-requests`;
};

/**
 * Fetches all certificate requests (admin only).
 *
 * Returns every request in the system, newest first. Used by the admin
 * dashboard to surface pending requests that need analysis or approval.
 *
 * @param adminSecret - Plaintext admin secret; sent as X-Admin-Secret header.
 * @param options     - Optional fetch overrides.
 * @returns           Array of all CertificateRequest documents.
 */
export const adminListRequests = async (
  adminSecret: string,
  options?: RequestInit,
): Promise<CertificateRequest[]> => {
  return customFetch<CertificateRequest[]>(getAdminListRequestsUrl(), {
    ...options,
    method: "GET",
    headers: {
      "X-Admin-Secret": adminSecret,
      ...options?.headers,
    },
  });
};

/**
 * Builds the React Query key for the admin requests list.
 * Include adminSecret in the key so each secret has its own cache entry —
 * prevents accidental leakage of one admin's data to another.
 *
 * @param adminSecret - The admin secret used for this query.
 */
export const getAdminListRequestsQueryKey = (
  adminSecret: string,
): readonly [string, string] => {
  return [`/api/admin/certificate-requests`, adminSecret] as const;
};

/**
 * Builds the full useQuery options object for adminListRequests.
 *
 * @param adminSecret - The admin secret used for authentication.
 * @param options     - Optional query options and request overrides.
 */
export const getAdminListRequestsQueryOptions = <
  TData = Awaited<ReturnType<typeof adminListRequests>>,
  TError = ErrorType<unknown>,
>(
  adminSecret: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminListRequests>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAdminListRequestsQueryKey(adminSecret);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof adminListRequests>>
  > = ({ signal }) =>
    adminListRequests(adminSecret, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof adminListRequests>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

/** Type alias for the resolved return value of adminListRequests. */
export type AdminListRequestsQueryResult = NonNullable<
  Awaited<ReturnType<typeof adminListRequests>>
>;
/** Type alias for the query error type. */
export type AdminListRequestsQueryError = ErrorType<unknown>;

/**
 * React Query hook for fetching all certificate requests (admin only).
 *
 * Pass `null` as `adminSecret` to disable the query — useful when the admin
 * secret has not yet been entered by the user.
 *
 * Usage:
 * ```tsx
 * const { data: requests } = useAdminListRequests(adminSecret);
 * ```
 *
 * @param adminSecret - Plaintext admin secret, or null to disable the query.
 * @param options     - Optional query options and request overrides.
 * @returns           UseQueryResult with data typed as CertificateRequest[].
 */
export function useAdminListRequests<
  TData = Awaited<ReturnType<typeof adminListRequests>>,
  TError = ErrorType<unknown>,
>(
  adminSecret: string | null,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof adminListRequests>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  // Disable the query when no secret is provided — prevents unauthenticated
  // requests from firing before the admin has entered their secret.
  const queryOptions = getAdminListRequestsQueryOptions(adminSecret ?? "", {
    ...options,
    query: {
      ...options?.query,
      queryKey: options?.query?.queryKey ?? getAdminListRequestsQueryKey(adminSecret ?? ""),
      enabled: adminSecret != null && (options?.query?.enabled ?? true),
    },
  });

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

// ---------------------------------------------------------------------------
// POST /api/admin/certificate-requests/{requestId}/analyze — Trigger pipeline
// ---------------------------------------------------------------------------

/**
 * Returns the URL for triggering analysis on a specific certificate request.
 *
 * @param requestId - The certificate request ID.
 */
export const getAdminTriggerAnalysisUrl = (requestId: string): string => {
  return `/api/admin/certificate-requests/${requestId}/analyze`;
};

/**
 * Triggers the full CarbonEYE pipeline for a certificate request (admin only).
 *
 * Moves status from "submitted" → "analyzing". When the pipeline completes,
 * the status automatically moves to "pending_approval". The admin can then
 * review the draft certificate and call adminApproveRequest or adminRejectRequest.
 *
 * This is the key human-in-the-loop gate: only an admin can start the pipeline.
 *
 * @param requestId   - The certificate request ID.
 * @param adminSecret - Plaintext admin secret; sent as X-Admin-Secret header.
 * @param options     - Optional fetch overrides.
 */
export const adminTriggerAnalysis = async (
  requestId: string,
  adminSecret: string,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getAdminTriggerAnalysisUrl(requestId), {
    ...options,
    method: "POST",
    headers: {
      "X-Admin-Secret": adminSecret,
      ...options?.headers,
    },
  });
};

/**
 * Builds the useMutation options object for adminTriggerAnalysis.
 */
export const getAdminTriggerAnalysisMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  adminSecret: string,
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminTriggerAnalysis>>,
      TError,
      { requestId: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseMutationOptions<
  Awaited<ReturnType<typeof adminTriggerAnalysis>>,
  TError,
  { requestId: string },
  TContext
> => {
  const mutationKey = ["adminTriggerAnalysis"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminTriggerAnalysis>>,
    { requestId: string }
  > = ({ requestId }) => {
    return adminTriggerAnalysis(requestId, adminSecret, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

/** Type alias for the mutation error type. */
export type AdminTriggerAnalysisMutationError = ErrorType<void>;

/**
 * React Query mutation hook for triggering pipeline analysis (admin only).
 *
 * Recommended pattern — invalidate the requests list after success so the
 * admin dashboard reflects the new "analyzing" status immediately:
 * ```tsx
 * const queryClient = useQueryClient();
 * const { mutate } = useAdminTriggerAnalysis(adminSecret, {
 *   mutation: {
 *     onSuccess: () => queryClient.invalidateQueries({
 *       queryKey: getAdminListRequestsQueryKey(adminSecret),
 *     }),
 *   },
 * });
 * mutate({ requestId });
 * ```
 *
 * @param adminSecret - Plaintext admin secret for X-Admin-Secret header.
 * @param options     - Optional mutation options and request overrides.
 */
export const useAdminTriggerAnalysis = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  adminSecret: string,
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminTriggerAnalysis>>,
      TError,
      { requestId: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseMutationResult<
  Awaited<ReturnType<typeof adminTriggerAnalysis>>,
  TError,
  { requestId: string },
  TContext
> => {
  return useMutation(
    getAdminTriggerAnalysisMutationOptions(adminSecret, options),
  );
};

// ---------------------------------------------------------------------------
// POST /api/admin/certificate-requests/{requestId}/approve — Approve request
// ---------------------------------------------------------------------------

/**
 * Returns the URL for approving a specific certificate request.
 *
 * @param requestId - The certificate request ID.
 */
export const getAdminApproveRequestUrl = (requestId: string): string => {
  return `/api/admin/certificate-requests/${requestId}/approve`;
};

/**
 * Approves a certificate request (admin only).
 *
 * Moves status from "pending_approval" → "approved". The certificate
 * immediately becomes visible to the requesting company via
 * GET /certificate-requests/{requestId}.
 *
 * @param requestId   - The certificate request ID.
 * @param adminSecret - Plaintext admin secret; sent as X-Admin-Secret header.
 * @param note        - Optional admin note surfaced to the company on approval.
 * @param options     - Optional fetch overrides.
 */
export const adminApproveRequest = async (
  requestId: string,
  adminSecret: string,
  note?: string,
  options?: RequestInit,
): Promise<void> => {
  // Build the body only when a note is provided — omit the body entirely when
  // there is nothing to send, avoiding a Content-Type header on an empty body.
  const body = note != null ? JSON.stringify({ note }) : undefined;

  return customFetch<void>(getAdminApproveRequestUrl(requestId), {
    ...options,
    method: "POST",
    headers: {
      "X-Admin-Secret": adminSecret,
      // Only set Content-Type when there is a body to send.
      ...(body != null ? { "Content-Type": "application/json" } : {}),
      ...options?.headers,
    },
    ...(body != null ? { body } : {}),
  });
};

/**
 * Builds the useMutation options object for adminApproveRequest.
 */
export const getAdminApproveRequestMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  adminSecret: string,
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminApproveRequest>>,
      TError,
      { requestId: string; note?: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseMutationOptions<
  Awaited<ReturnType<typeof adminApproveRequest>>,
  TError,
  { requestId: string; note?: string },
  TContext
> => {
  const mutationKey = ["adminApproveRequest"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminApproveRequest>>,
    { requestId: string; note?: string }
  > = ({ requestId, note }) => {
    return adminApproveRequest(requestId, adminSecret, note, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

/** Type alias for the mutation error type. */
export type AdminApproveRequestMutationError = ErrorType<void>;

/**
 * React Query mutation hook for approving a certificate request (admin only).
 *
 * Recommended pattern — invalidate both the list and the individual request
 * query after success so the admin dashboard and company portal update:
 * ```tsx
 * const { mutate } = useAdminApproveRequest(adminSecret, {
 *   mutation: {
 *     onSuccess: (_, { requestId }) => {
 *       queryClient.invalidateQueries({ queryKey: getAdminListRequestsQueryKey(adminSecret) });
 *       queryClient.invalidateQueries({ queryKey: getGetCertificateRequestQueryKey(requestId) });
 *     },
 *   },
 * });
 * mutate({ requestId, note: 'Looks correct — approved.' });
 * ```
 *
 * @param adminSecret - Plaintext admin secret for X-Admin-Secret header.
 * @param options     - Optional mutation options and request overrides.
 */
export const useAdminApproveRequest = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  adminSecret: string,
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminApproveRequest>>,
      TError,
      { requestId: string; note?: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseMutationResult<
  Awaited<ReturnType<typeof adminApproveRequest>>,
  TError,
  { requestId: string; note?: string },
  TContext
> => {
  return useMutation(
    getAdminApproveRequestMutationOptions(adminSecret, options),
  );
};

// ---------------------------------------------------------------------------
// POST /api/admin/certificate-requests/{requestId}/reject — Reject request
// ---------------------------------------------------------------------------

/**
 * Returns the URL for rejecting a specific certificate request.
 *
 * @param requestId - The certificate request ID.
 */
export const getAdminRejectRequestUrl = (requestId: string): string => {
  return `/api/admin/certificate-requests/${requestId}/reject`;
};

/**
 * Rejects a certificate request (admin only).
 *
 * Moves the request to the terminal "rejected" state and records the reason.
 * The rejection_reason is surfaced to the requesting company via
 * GET /certificate-requests/{requestId}. Once rejected, no further state
 * transitions are possible.
 *
 * @param requestId   - The certificate request ID.
 * @param adminSecret - Plaintext admin secret; sent as X-Admin-Secret header.
 * @param reason      - Human-readable rejection reason; required by the API.
 * @param options     - Optional fetch overrides.
 */
export const adminRejectRequest = async (
  requestId: string,
  adminSecret: string,
  reason: string,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getAdminRejectRequestUrl(requestId), {
    ...options,
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Admin-Secret": adminSecret,
      ...options?.headers,
    },
    body: JSON.stringify({ reason }),
  });
};

/**
 * Builds the useMutation options object for adminRejectRequest.
 */
export const getAdminRejectRequestMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  adminSecret: string,
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminRejectRequest>>,
      TError,
      { requestId: string; reason: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseMutationOptions<
  Awaited<ReturnType<typeof adminRejectRequest>>,
  TError,
  { requestId: string; reason: string },
  TContext
> => {
  const mutationKey = ["adminRejectRequest"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminRejectRequest>>,
    { requestId: string; reason: string }
  > = ({ requestId, reason }) => {
    return adminRejectRequest(requestId, adminSecret, reason, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

/** Type alias for the mutation error type. */
export type AdminRejectRequestMutationError = ErrorType<void>;

/**
 * React Query mutation hook for rejecting a certificate request (admin only).
 *
 * Recommended pattern — invalidate both the list and the individual request
 * after success so the admin dashboard and company portal update:
 * ```tsx
 * const { mutate } = useAdminRejectRequest(adminSecret, {
 *   mutation: {
 *     onSuccess: (_, { requestId }) => {
 *       queryClient.invalidateQueries({ queryKey: getAdminListRequestsQueryKey(adminSecret) });
 *       queryClient.invalidateQueries({ queryKey: getGetCertificateRequestQueryKey(requestId) });
 *     },
 *   },
 * });
 * mutate({ requestId, reason: 'Coordinates are outside the monitored region.' });
 * ```
 *
 * @param adminSecret - Plaintext admin secret for X-Admin-Secret header.
 * @param options     - Optional mutation options and request overrides.
 */
export const useAdminRejectRequest = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  adminSecret: string,
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof adminRejectRequest>>,
      TError,
      { requestId: string; reason: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseMutationResult<
  Awaited<ReturnType<typeof adminRejectRequest>>,
  TError,
  { requestId: string; reason: string },
  TContext
> => {
  return useMutation(
    getAdminRejectRequestMutationOptions(adminSecret, options),
  );
};
