/**
 * lib/api-client-react/src/index.ts — Public API exports combining orval-generated React Query client, schemas, and hand-written certificate-request hooks with auth configuration functions.
 * Author: Pasquale Marzaioli
 */
export * from "./generated/api";
export * from "./generated/api.schemas";
export { setBaseUrl, setAuthTokenGetter } from "./custom-fetch";
export type { AuthTokenGetter } from "./custom-fetch";
// Certificate request workflow (human-in-the-loop approval flow).
// Hand-written — not generated by orval — because it uses @workspace/carboneye-types.
export * from "./certificate-requests";
